# Generated by Django 3.0.8 on 2020-07-08 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=250, verbose_name='Название блюда')),
                ('url', models.URLField(blank=True, default='', help_text='Ссылка на картинку', verbose_name='URL картинки')),
                ('amount', models.DecimalField(decimal_places=2, default=1, max_digits=15, verbose_name='Цена блюда')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(default='', max_length=50)),
                ('name', models.CharField(default='', max_length=70)),
                ('isAdmin', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('lastLogin', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('customer', models.CharField(default='', help_text='заказчик', max_length=200)),
                ('totalDishes', models.IntegerField(default=1, help_text='Итого. Кол-во блюд')),
                ('totalCount', models.IntegerField(default=1, help_text='Итого. Кол-во позиций')),
                ('totalAmount', models.DecimalField(decimal_places=2, default=0, help_text='Итого. Сумма', max_digits=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catering.User')),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1, help_text='Количество позиций')),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='Сумма за позицию', max_digits=15)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catering.Order')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catering.Recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catering.User')),
            ],
        ),
    ]
