# Generated by Django 3.0.8 on 2020-07-08 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
