# Generated by Django 3.0.8 on 2020-07-10 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catering', '0003_auto_20200709_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='user',
            field=models.ForeignKey(default=1, help_text='Оператор заказа', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(default=1, help_text='Оператор заказа', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
